### ISSUE TITLE
Fails to download updated packages from Slackware Repo

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#29]
I'm on Slackware 64bit 14.1 and I set slpkg to use current packages. However after doing "slpkg upgrade" and trying to update my Slackware packages from the official mirror (slpkg -c slack --upgrade), it seems to fail download them:

[1/12][ Download ] --> python-2.7.10-x86_64-1.txz

--2015-07-14 19:37:17--  http://mirrors.slackware.com/slackware/slackware64-current/slackware64/d/python-2.7.10-x86_64-1.txz
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-14 19:37:18 ERROR 404: Not Found.

+==============================================================================
| Download 'python-2.7.10-x86_64-1.txz' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]?

Any reason for this?

**Comment by dslackw** [comment]
Change mirror from :
```
/etc/slpkg/slackware-mirrors

```

**Comment by Xylemon** [comment]
I'm curious, why is it referencing files that are apparently updated on mirrors.slackware.com but in reality it's not?

**Comment by BrentonEarl** [comment]
Did run slpkg update && slpkg upgrade?

**Comment by Xylemon** [comment]
Yes.

**Comment by BrentonEarl** [comment]
I am running slackware64-current and I get the following when I check for the files on that mirror:

```bash
facerip@darkstar[~]$ lftp ftp://mirrors.slackware.com/slackware/slackware64-current/slackware64/d/
cd ok, cwd=/slackware/slackware64-current/slackware64/d                                        
lftp mirrors.slackware.com:/slackware/slackware64-current/slackware64/d> ls *python*
-rw-r--r--    1 903      903           438 Mar 23 01:13 python-2.7.9-x86_64-1.txt
-rw-r--r--    1 903      903      14210320 Mar 23 01:13 python-2.7.9-x86_64-1.txz
-rw-r--r--    1 903      903           181 Mar 23 01:13 python-2.7.9-x86_64-1.txz.asc
-rw-r--r--    1 903      903           513 Mar 18 21:48 python-setuptools-14.3-x86_64-1.txt
-rw-r--r--    1 903      903        300240 Mar 18 21:48 python-setuptools-14.3-x86_64-1.txz
-rw-r--r--    1 903      903           181 Mar 18 21:48 python-setuptools-14.3-x86_64-1.txz.asc
lftp mirrors.slackware.com:/slackware/slackware64-current/slackware64/d> 
```

You should try a fresh install of slpkg.

**Comment by BrentonEarl** [comment]
I can confirm the same download error on a fresh install of Slackware64-current and a fresh install of slpkg 2.6.1.

Furthermore, the following command gives a connection refused. 
```bash
lftp https://mirrors.slackware.com/slackware/slackware64-current/slackware64/d/
```

**Comment by Xylemon** [comment]
Yeah I just did a fresh install and still had the same problem.

**Comment by BrentonEarl** [comment]
A lot of changes have been made to slpkg if you check out the latest commits.  Looks like some clean up and adjustments may be affecting the latest few versions of slpkg.  You can downgrade to an older version of slpkg, but @dslackw usually fixes things pretty quickly.

**Comment by dslackw** [comment]
Thank you guys, fixed in develop branch.

**Comment by Xylemon** [comment]
Good to hear, I'll give it a try next release.

**Comment by Xylemon** [comment]
I still get this with latest release, but maybe this isn't an issue with Slpkg? Looking at: http://mirrors.slackware.com/slackware/slackware64-current/slackware64/
Slpkg crawls the "PACKAGES.TXT" from here as it should. However, the "PACKAGES.TXT" here links to one from a mirror that has updated packages. So Slackware's site is using another "PACKAGES.TXT" that is updated while the website is still using older packages. Rather odd...

**Comment by dslackw** [comment]
Yes, it has been observed this last the central website for Slackware. You can change the mirror from the file "/etc/slpkg/slackware-mirros" or add your own.

**Comment by Xylemon** [comment]
@dslackw Yes I was doing just that but something went horribly wrong. I choose Alien's mirror (since that's where Slackware is getting its package list), however slpkg was incorrectly crawling the wrong site. It grabs from both "http://taper.alienbase.nl/mirrors/slackware/slackware64-current/pasture/" and "http://taper.alienbase.nl/mirrors/slackware/slackware64-current/", and "http://taper.alienbase.nl/mirrors/slackware/slackware64-current/pasture/" does not exists so upon doing "slpkg update" I am unable to download the needed files from the incorrect url which leaves me unable to update any packages. Why is slpkg going to the wrong site location for Alien's mirror?

**Comment by dslackw** [comment]
In the official Slackware's mirrors directories "pasture/" and "extra/" exist. I don't know why Eric let out.

**Comment by dslackw** [comment]
Try to choose from here http://mirrors.slackware.com/mirrorlist/

**Comment by BrentonEarl** [comment]
I've had a lot of luck with the following mirror.  It's located in Salt Lake City, Utah.  They update it 1-2 hours behind mirrors.slackware.com and any trouble I've had with errors was answered promptly by their tech support.

```bash
http://mirrors.xmission.com/slackware/slackware64-current/
```

**Comment by Xylemon** [comment]
I tried the kernel.org mirrors and everything downloaded fine. Closing since not a slpkg issue, but rather a Slackware site issue I suppose.
